export const SET_CART_POSITIONS_QUANTITY = 'SET_CART_POSITIONS_QUANTITY';

export const ADD_SHIPPING_INFO = 'ADD_SHIPPING_INFO';
export const ADD_BILLING_INFO = 'ADD_BILLING_INFO';
export const ADD_PAYMENT_INFO = 'ADD_PAYMENT_INFO';

export const MAKE_ORDER = 'MAKE_ORDER';
export const MAKE_ORDER_START = 'MAKE_ORDER_START';
export const MAKE_ORDER_SUCCESS = 'MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_FAIL = 'MAKE_ORDER_FAIL';
